name: Lectura de variables desde otro YMAL

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      comment:
        type: choice
        description: Comentar lineas
        default: uncomment
        options: 
        - comment
        - uncomment
      

jobs:
  Lectura_configVars_YAML:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        
      - name: Descargar yq # Referencia: https://github.com/mikefarah/yq
        # 1) Descargar el archivo tar.gz
        # 2) Extraer el archivo .tar.gz al directorio de trabajo actual
        # 3) Moverlo a /usr/local/bin/
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64.tar.gz
          tar xf yq_linux_amd64.tar.gz
          mv yq_linux_amd64 /usr/local/bin/

        ###############
        # Diccionario #
        ###############
      - name: Leer variables del archivo config_vars.yml
        id: dict
        run: |
          echo "clave1=$(cat config_vars.yml | yq eval '.mi_diccionario.clave1' -r)" >> $GITHUB_OUTPUT
          echo "subclave1=$(cat config_vars.yml | yq eval '.mi_diccionario.clave2.subclave1' -r)" >> $GITHUB_OUTPUT
          echo "subclave2=$(cat config_vars.yml | yq eval '.mi_diccionario.clave2.subclave2' -r)" >> $GITHUB_OUTPUT
          echo "clave3=$(cat config_vars.yml | yq eval '.mi_diccionario.clave3' -r)" >> $GITHUB_OUTPUT
        
      - name: Usar las variables como mi_diccionario en otro paso
        run: |
          echo "Valor de clave1: ${{ steps.dict.outputs.clave1 }}"
          echo "Valor de clave2.subclave1: ${{ steps.dict.outputs.subclave1 }}"
          echo "Valor de clave2.subclave2: ${{ steps.dict.outputs.subclave2 }}"
          echo "Valor de clave3: ${{ steps.dict.outputs.clave3 }}"
          

        #################
        # Ejecutar BASH #
        #################
      - name: Leer variable desde el workflow
        run: |
          echo "Nombre: ${{ github.event.inputs.comment }}"

      - name: Ejecutar script Bash
        run: bash ./file.sh -c "${{ github.event.inputs.comment }}"

        #####################
        # Crear diccionario #
        #####################
      - name: Crear Todos var
        id: JSON_CONTENT
        run: |
          echo "JSON_CONTENT=$(cat config_vars.yml | yq eval '.mi_diccionario' -r)" >> $GITHUB_OUTPUT

      - name: Leer variable desde el workflow
        run: |
          echo "JSON_CONTENT: ${{ steps.JSON_CONTENT.outputs.clave1 }}"
      


     
