name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main
      - 'fix/**'
      - 'test/**'

  workflow_dispatch:
    inputs:
      dynamodb:
        description: 'Activa la insercion de datos de la carpeta tablas DynamoDB'
        required: false
        default: false
        type: boolean

jobs:
  mi_trabajo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        
      - name: Descargar yq-go
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64.tar.gz
          tar xvf yq_linux_amd64.tar.gz
          mv yq_linux_amd64 /usr/local/bin/
        
      - name: Leer variables del archivo variables.yml
        id: vars
        run: |
          mv variables.yml /usr/local/bin/
          echo "::set-output name=var1::$(cat variables.yml | yq eval '.variables.var1' -)"
        
      - name: Usar las variables en otro paso
        run: |
          echo "La variable var1 es ${{ steps.vars.outputs.var1 }}"
