name: Lectura de variables desde YMAL

on:
  push:
    branches:
      - main

jobs:
  Lectura_YAML:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
        
      - name: Descargar yq # Referencia: https://github.com/mikefarah/yq
        # 1) Descargar el archivo tar.gz
        # 2) Extraer el archivo .tar.gz al directorio de trabajo actual
        # 3) Moverlo a /usr/local/bin/
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64.tar.gz
          tar xf yq_linux_amd64.tar.gz
          mv yq_linux_amd64 /usr/local/bin/
        
      - name: Leer variables del archivo my_vars.yml
        id: vars
        run: |
          echo "::set-output name=var1::$(cat my_vars.yml | yq eval '.variables.var1' -)"
        
      - name: Usar las variables en otro paso
        run: |
          echo "La variable var1 es ${{ steps.vars.outputs.var1 }}"

        #############################
        # Diccoinario o propiedades #
        #############################

      - name: Leer variables del archivo config_vars.yml como mi_diccionario
        id: vars_prop
        run: |
          echo "::set-output name=mi_diccionario::$(cat config_vars.yml | yq eval '.mi_diccionario' -)"
        
      - name: Usar las variables como mi_diccionario en otro paso
        run: |
          echo "clave1: ${{ steps.vars_prop.outputs.mi_diccionario.clave1 }}"
          echo "clave2.subclave1: ${{ steps.vars_prop.outputs.mi_diccionario.clave2.subclave1 }}"
          echo "clave2.subclave2: ${{ steps.vars_prop.outputs.mi_diccionario.clave2.subclave2 }}"
          echo "clave3: ${{ steps.vars_prop.outputs.mi_diccionario.clave3 }}"

      - name: Leer variables del archivo others.yml
        id: vars2
        run: |
          echo "::set-output name=lista::$(cat other.yml | yq eval '.Var_mix.lista' -)"
        
      - name: Usar las variables en otro paso
        run: |
          echo "La variable lista es ${{ steps.vars2.outputs.lista }}"
          echo "La variable lista[0] es ${{ steps.vars2.outputs.lista[0] }}"
